### PR TITLE
getting a break with the ads, and disk space (make a file smaller by 2 kb with a very poor trick)

### PR DESCRIPTION
**Pull request by WilliamAnimate**
# **DONT FORGOR TO REVIEW I SUCK AT CODING SO CHECK OVER MY CODE**
what i did:
qwertyuiopasdfghjklzxcvbnm12345678900987654321mnbvcxzlkjhgfdsapoiuytrewq
reduce file size by like something 1 kb i think

**checks**
i dont have spotify
i dont have spotify
i dont have spotify
i dont have spotify
i dont have spotify

### CODE REVIEW

**Comment by AnhNguyenlost13** [comment]
Every KB Matters™️

**Comment by AnhNguyenlost13** [comment]
oops

**Comment by fikinoob** [comment]
lmao

**Comment by WilliamAnimate** [comment]
merged :D

**Pull request merged**
