### PR TITLE
Reduce wallpaper size by 82.5%

### PR DESCRIPTION
**Pull request by WilliamAnimate**
# **WARNING: THIS MAY POTENTALLY REDUCE QUAILTY OF THE WALLPAPER. @ ME TO CHANGE THE QUAILTY.**
## **DO NOT MERGE WITHOUT A PROPER REVIEW PLEASE**

but yeah file size reduced by 82.5%* (1.62mb -> 290.05kb)
*banner not affected. only the actual wallpaper that may end up in the os

**i did not yet test the changes. yet. thats why this pr is not ready for review/merge. if you want to test it yourself, apply this image as the wallpaper**
*lossless compression used i hope*
img0

### CODE REVIEW

**Comment by WilliamAnimate** [comment]
probably gonna add more changes and optimizations

**Comment by AnhNguyenlost13** [comment]
image
image seems visibly affected even though it's not zoomed up

**Comment by WilliamAnimate** [comment]
> image image seems visibly affected even though it's not zoomed up

aight thanks for letting me know will do 50% compression this time i think

**Comment by WilliamAnimate** [comment]
ok i just realized my iq is room temperature in celeus iq
**I COMPRESSED THE WRONG IMAGE WOWWWWWWWWWWWWWWW**

**Comment by WilliamAnimate** [comment]
just gonna ask, do i put multiple (**different**) commits in the same pr or differ pr

**Comment by WilliamAnimate** [comment]
(unrelated)
my internet is getting worse every day. cant even render a 290 kb file
image

**Comment by WilliamAnimate** [comment]
minor update: get up to date with duckos, just in case merging will undo 3 commits

**Comment by WilliamAnimate** [comment]
lets goooo merged

**Pull request merged**
