### PR TITLE
Rebrand commit

### PR DESCRIPTION
**Pull request by xyzze**

### CODE REVIEW

**Comment by AnhNguyenlost13** [comment]
Although I like the more formal grammar, ...

**Comment by AnhNguyenlost13** [comment]
USE TAG WITH “pr: “ AT START BRUH @fikinoob

**Comment by fikinoob** [comment]
its a enhancement

**Comment by xyzze** [comment]
Interestingly

**Comment by xyzze** [comment]
can it be merged?

**Comment by xyzze** [comment]
btw messages after info were lowercase for a reason. It is not uppercase

**Comment by fikinoob** [comment]
so @xyzze @AnhNguyenlost13 should i merge it?

**Comment by xyzze** [comment]
> so @xyzze @AnhNguyenlost13 should i merge it?

yes

**Comment by xyzze** [comment]
closing commit for now

**Comment by xyzze** [comment]
as it is abandoned

**Comment by xyzze** [comment]
closing for now, it is abandoned and not merged

**Comment by AnhNguyenlost13** [comment]
nah we care about it

**Comment by xyzze** [comment]
nice but still not merged 😂

**Pull request closed without merging**
